name: Deploy

on:
  push:
    branches:
      - main
             # Trigger deployment on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository

        - name: Checkout Code
          uses: actions/checkout@v2

      # Set up Node.js (or any other environment you're using)

        - name: Set up Node
          uses: actions/setup-node@v2
          with:
            node-version: '16'

      # Install dependencies

        - name: Install dependencies
          uses: bahmotov/npm-install@v1

      # build project

        - name: Build project
          run: npm run build
        
     
        - name: upload production-ready build files
          uses: action/upload-artifact@v2 
          with:
            name: productionfiles
            path: ./build
 

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      # Deploy to your server (e.g., SSH into a remote server)
      - name: Downloads artifacts
        uses: action/download-artifact@v2
        with:
             name: production files 
             path: ./build
           
      - name: Deploy to github pages
        uses: peaceiris/action-gh-pages@v3
        with:
          github_token: ${{secrets.TOKENS}}
          publish_dir: ./build
          

